source 'http://rubygems.org'

gem 'thin'
gem 'sinatra'
gem 'rqrcode'
gem 'markdown'
gem 'rdiscount'
gem 'redcarpet'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-openid'
gem 'omniauth-google-oauth2'
